### ISSUE TITLE
Bug: `rstuf admin ceremony -b -u` has exception

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-cli#312]
### What happened?

Using the CLI to perform the ceremony bootstrap, it gets an exception.

```shell
❯ rstuf --version
rstuf, version 0.3.0a1
```

As explained in the [bootstrap section](https://repository-service-tuf.readthedocs.io/en/v1.0.0a1-draft/guide/deployment/setup.html#bootstrap).

`rstuf admin ceremony -b -u`

It doesn't fail gracefully.

```shell
❯ rstuf admin ceremony -b -u
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/rstuf", line 8, in <module>
    sys.exit(rstuf())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/rich_click/rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/kdearaujo/devel/RSTUF/repository-service-tuf-cli/repository_service_tuf/cli/admin/ceremony.py", line 671, in ceremony
    bs_status = bootstrap_status(settings)
  File "/Users/kdearaujo/devel/RSTUF/repository-service-tuf-cli/repository_service_tuf/helpers/api_client.py", line 128, in bootstrap_status
    settings.SERVER, URL.bootstrap.value, Methods.get, headers=headers
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dynaconf/base.py", line 136, in __getattr__
    value = getattr(self._wrapped, name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dynaconf/base.py", line 298, in __getattribute__
    return super().__getattribute__(name)
AttributeError: 'Settings' object has no attribute 'SERVER'
```

### What steps did you take?

1. Install the repository-service-tuf 0.3.0a1: `pip install repository-service-tuf`
2. Run the ceremony bootstrap upload: `rstuf admin ceremony -b -u`

### Relevant log output

```shell
❯ rstuf admin ceremony -b -u
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/rstuf", line 8, in <module>
    sys.exit(rstuf())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/rich_click/rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/kdearaujo/devel/RSTUF/repository-service-tuf-cli/repository_service_tuf/cli/admin/ceremony.py", line 671, in ceremony
    bs_status = bootstrap_status(settings)
  File "/Users/kdearaujo/devel/RSTUF/repository-service-tuf-cli/repository_service_tuf/helpers/api_client.py", line 128, in bootstrap_status
    settings.SERVER, URL.bootstrap.value, Methods.get, headers=headers
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dynaconf/base.py", line 136, in __getattr__
    value = getattr(self._wrapped, name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dynaconf/base.py", line 298, in __getattribute__
    return super().__getattribute__(name)
AttributeError: 'Settings' object has no attribute 'SERVER'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
### Workaround

Add the `--upload-server`  parameter

`rstuf admin ceremony -b -u --upload-server http://127.0.0.1`
