### ISSUE TITLE
Task: review & improve if needed UI and UX of `admin2` commands

### ISSUE THREAD

**Issue by MVrachev** [repository-service-tuf/repository-service-tuf-cli#534]
### What is the task about?

Compare UI and UX between `admin2` commands and current corresponding commands.

This will be an umbrella issue for UI and UX improvements for each of the commands.

### Parent feature

https://github.com/repository-service-tuf/repository-service-tuf-cli/issues/532

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
Adding here as a note for error handling in the user UI/UX

```python
Please enter path to encrypted private key: tests/files/key_storage/online1.key
Please enter password: 
Traceback (most recent call last):
  File "/Users/kairo/.local/share/virtualenvs/repository-service-tuf-cli-EVsxK5JG/bin/rstuf", line 8, in <module>
    sys.exit(rstuf())
  File "/Users/kairo/.local/share/virtualenvs/repository-service-tuf-cli-EVsxK5JG/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kairo/.local/share/virtualenvs/repository-service-tuf-cli-EVsxK5JG/lib/python3.9/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
  File "/Users/kairo/.local/share/virtualenvs/repository-service-tuf-cli-EVsxK5JG/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kairo/.local/share/virtualenvs/repository-service-tuf-cli-EVsxK5JG/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kairo/.local/share/virtualenvs/repository-service-tuf-cli-EVsxK5JG/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kairo/.local/share/virtualenvs/repository-service-tuf-cli-EVsxK5JG/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/kairo/dev/RSTUF/repository-service-tuf-cli/repository_service_tuf/cli/admin2/ceremony.py", line 91, in ceremony
    _add_root_signatures_prompt(root_md, None)
  File "/Users/kairo/dev/RSTUF/repository-service-tuf-cli/repository_service_tuf/cli/admin2/helpers.py", line 415, in _add_root_signatures_prompt
    _add_signature_prompt(root_md, key)
  File "/Users/kairo/dev/RSTUF/repository-service-tuf-cli/repository_service_tuf/cli/admin2/helpers.py", line 377, in _add_signature_prompt
    signer = _load_signer_from_file_prompt(key)
  File "/Users/kairo/dev/RSTUF/repository-service-tuf-cli/repository_service_tuf/cli/admin2/helpers.py", line 142, in _load_signer_from_file_prompt
    private_key = load_pem_private_key(private_pem, password.encode())
TypeError: Password was given but private key is not encrypted.
```

**Comment by lukpueh** [comment]
> ... and `cryptography.exceptions.UnsupportedAlgorithm`, which may also be [raised by `load_pem_private__key`](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/#cryptography.hazmat.primitives.serialization.load_pem_private_key).

`UnsupportedAlgorithm` may be also [raised in `load_pem_public_key`](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/#cryptography.hazmat.primitives.serialization.load_pem_public_key), so we should also except it here:

https://github.com/repository-service-tuf/repository-service-tuf-cli/blob/6bbf1e809695bc388a9084e51bd20ab455573a47/repository_service_tuf/cli/admin2/helpers.py#L164
